# Bei jedem Push auf den main Branch wird Deployment-Prozess ausgeführt
# Führt die Terraform Befehle im Ordner infrastructure aus
# Die Zugangsdaten zu AWS werden aus den GitHub Secrets des Repositorys gelesen
# Apply wird automatisch ohne manuelle Bestätigung ausgeführt

name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Terraform installieren
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform initialisieren
        run: terraform init
        working-directory: infrastructure

      - name: Lambda Code zippen
        run: zip -r backend.zip . -x "*.git*" -x "*.terraform*" -x "node_modules/*"
        working-directory: backend

      - name: Terraform Plan ausführen
        run: terraform plan
        working-directory: infrastructure

#       - name: Terraform Apply ausführen
#         run: terraform apply -auto-approve
#         working-directory: infrastructure
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# 