name: Upload WebApp in  S3-Bucket

on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'

jobs:
  deploy-webapp:
    name: WebApp bauen und in S3-Bucket hochladen
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Abhängigkeiten installieren
        run: |
          cd webapp
          npm install

      - name: WebApp bauen
        run: |
          cd webapp
          npm run build

      - name: Dateien in S3 hochladen
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: samtpfoten-lounge
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          SOURCE_DIR: webapp/dist
